### ISSUE TITLE
Errors on installing

### ISSUE THREAD

**Issue by leontedev** [TehShrike/backup-bear-notes#11]
I'm getting a lot of errors on installing. Tried to use sudo as well, but it doesn't work. This is on MacOS Catalina 10.15.3. Any pointers? 
[errors.txt](https://github.com/TehShrike/backup-bear-notes/files/4253941/errors.txt)

**Comment by TehShrike** [comment]
Searching around the internet, I found https://github.com/nodejs/node-gyp/issues/1779 and from there I found https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md
