### ISSUE TITLE
Slash replacement only replaces first instance

### ISSUE THREAD

**Issue by gordonbazeley** [TehShrike/backup-bear-notes#4]
I noted that the slash replacement was replacing e.g. 23/01/2020 with 23-01/2020.

This article explains why this is the case - https://stackoverflow.com/questions/1967119/why-does-javascript-replace-only-first-instance-when-using-replace

The fix appears to be to change the slash replacement to:
const filename = `${ title.replace(/\//g, "-") }.md`

**Comment by TehShrike** [comment]
Yup, you're right!

Willing to open a PR?
